version: "3.8"
services:
  front_web:
    build:
      context: ./front_web
      target: dev # 使用 Dockerfile 中的开发阶段
    ports:
      - "3000:3000"
    volumes:
      - ./front_web:/app # 假设源代码在 /app 目录
      - /app/node_modules # 排除 node_modules 目录
    environment:
      - NODE_ENV=development
    command: yarn dev # 假设使用 yarn dev 启动开发服务器

  front_admin:
    build:
      context: ./front_admin
      target: dev
    ports:
      - "3001:3000"
    volumes:
      - ./front_admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev

  back_api:
    build:
      context: ./back_api
      target: development # 使用 Dockerfile 中的开发阶段
    ports:
      - "8000:8000"
    volumes:
      - ./back_api:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports: # 映射端口外部才能访问
      - "3306:3306"
